apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opencloud

resources:
  - admin-secret.yaml
  - pvc-opencloud-config.yaml
  - pvc-opencloud-data.yaml
  - pvc-opencloud-apps.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - envs:
      - opencloud-envs.env
    name: opencloud-envs

images:
  - name: opencloudeu/opencloud-rolling
    newTag: 4.1.0
