apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.19.3/cert-manager.yaml
  - issuer.yaml
  - secret.yaml

patches:
  - path: args.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: cert-manager
