apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kgateway-crds
spec:
  chart:
    spec:
      chart: kgateway-crds
      version: v2.1.1
      sourceRef:
        kind: HelmRepository
        name: kgateway
  targetNamespace: kgateway
  releaseName: kgateway-crds
  interval: 1m0s
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kgateway
spec:
  chart:
    spec:
      chart: kgateway
      version: v2.1.1
      sourceRef:
        kind: HelmRepository
        name: kgateway
  targetNamespace: kgateway
  releaseName: kgateway
  interval: 1m0s
  dependsOn:
    - name: kgateway-crds
