apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kgateway-crds
spec:
  interval: 5m0s
  url: oci://cr.kgateway.dev/kgateway-dev/charts/kgateway-crds
  ref:
    tag: v2.1.2
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kgateway
spec:
  interval: 5m0s
  url: oci://cr.kgateway.dev/kgateway-dev/charts/kgateway
  ref:
    tag: v2.1.1
