apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prometheus-community
  namespace: victoria-metrics
spec:
  interval: 15m
  url: oci://ghcr.io/prometheus-community/charts/prometheus-operator-crds
  ref:
    tag: 26.0.0
