apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kromgo
spec:
  parentRefs:
    - name: public
      namespace: kgateway
      sectionName: https
  hostnames:
    - kromgo.p6r.dev
  rules:
    - backendRefs:
        - name: kromgo
          port: 80
