apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kromgo

images:
  - name: ghcr.io/kashalls/kromgo
    newTag: v0.7.5

resources:
  - deployment.yaml
  - service.yaml
  - httproute.yaml

configMapGenerator:
  - name: kromgo-config
    files:
      - config.yaml
