apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: github-runner-scale-set-controller
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
  ref:
    tag: 0.13.1
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: github-runner-scale-set
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
  ref:
    tag: 0.13.1
