apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns

images:
  - name: registry.k8s.io/external-dns/external-dns
    newTag: v0.20.0
  - name: ghcr.io/muhlba91/external-dns-provider-adguard
    newTag: v11.0.2

resources:
  - bundle.yaml
  - secret.yaml
